### ISSUE TITLE
RED-19: Grid bugfix

### ISSUE THREAD

**Issue by szoki-moki** [ng201/Tower-Defense-RED#92]
Sajnos a grid elszáll, ha nem négyzet alakú pályát akarunk tárolni benne. Ha jól látom, az initmapban fel vannak cserélve a koordináták talán, illetve a cellánál is van valami bibi, mert ha az initmapon túl is jut, még mindig meghal. (A generálás közben jött elő a probléma, ott lehet téglalap alakú pályát generálni, tehát még az is előfordulhat, hogy azzal is van hiba.)

**Comment by KissG549** [comment]
done
